"""Internal layout types for grounded document parsing.

These types validate the parser's block geometry and JSON artifact. They are
not a user-defined field extraction schema.

Must not: give model-facing page/block models a field with a Python default (breaks
OpenAI's strict json_schema mode -- see the comment block below and
docs/MODEL.md) or a fixed-length tuple type.

Next: src/parse.py for how these types are populated.
"""

from __future__ import annotations

import math
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from src.diagnostics import PageDiagnostic, LayoutFailureStage
from src.config import max_table_cells

# OpenAI's structured-outputs strict mode (with_structured_output(..., method="json_schema"))
# requires every property in `required` (no field may rely on a Python default to be
# "optional" -- use a nullable type instead) and does not support fixed-length tuple
# validation (`prefixItems`, generated by e.g. tuple[float, float, float, float]). Every
# model sent to the model is shaped to satisfy both constraints; see docs/MODEL.md.


def _require_xyxy_len(v: tuple[float, ...]) -> tuple[float, ...]:
    if len(v) != 4:
        raise ValueError("xyxy must have exactly 4 values (x0, y0, x1, y1)")
    return v


def expanded_table_cells(rows: list[list[str]]) -> int:
    """Count cells after rectangular padding, including omitted trailing blanks."""
    return len(rows) * max((len(row) for row in rows), default=0)


def check_document_tables(pages) -> None:
    # Leave malformed shapes to Pydantic's ordinary field validation.
    """Reject a document whose rectangularized tables exceed the cell budget.

    Accept raw page dictionaries or page models. Malformed shapes are left to
    field validation. Raise ValueError when the accumulated budget is exceeded.
    """
    if not isinstance(pages, (list, tuple)):
        return
    total = 0
    for page in pages:
        blocks = page.get("blocks", []) if isinstance(page, dict) else getattr(page, "blocks", [])
        if not isinstance(blocks, (list, tuple)):
            continue
        for block in blocks:
            rows = block.get("table") if isinstance(block, dict) else getattr(block, "table", None)
            if rows is not None and (not isinstance(rows, list) or not all(isinstance(row, list) for row in rows)):
                continue
            total += expanded_table_cells(rows or [])
            if total > max_table_cells():
                raise ValueError("Expanded tables exceed GROUNDMARK_MAX_TABLE_CELLS")


def _bounded_blocks(value):
    check_document_tables([{"blocks": value}])
    return value


class BBox(BaseModel):
    model_config = ConfigDict(extra="forbid")

    page: int  # 1-based
    xyxy: tuple[float, ...]  # normalized 0-1, exactly 4 values (x0, y0, x1, y1)

    _check_xyxy = field_validator("xyxy")(_require_xyxy_len)


class ListItem(BaseModel):
    model_config = ConfigDict(extra="forbid")
    text: str
    marker: str
    depth: int = Field(ge=0, le=12)
    checked: bool | None


class TableCell(BaseModel):
    model_config = ConfigDict(extra="forbid")
    row: int = Field(ge=0)
    column: int = Field(ge=0)
    rowspan: int = Field(ge=1)
    colspan: int = Field(ge=1)
    is_header: bool


class BlockStructure(BaseModel):
    model_config = ConfigDict(extra="forbid")
    heading_level: Literal[1, 2, 3, 4, 5, 6] | None
    list_items: list[ListItem] | None
    table_cells: list[TableCell] | None


class LegacyBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    type: Literal[
        "title", "heading", "text", "list", "table", "key_value", "figure", "marginalia", "other"
    ]
    text: str
    bbox: BBox | None
    conf: float | None
    table: list[list[str]] | None  # rows, only when type == "table"

    @field_validator("table")
    @classmethod
    def _rectangularize_table(cls, value: list[list[str]] | None) -> list[list[str]] | None:
        """Preserve cells while padding omitted trailing blanks in model output."""
        if not value:
            return value
        width = max(len(row) for row in value)
        if len(value) * width > max_table_cells():
            raise ValueError("Expanded table exceeds GROUNDMARK_MAX_TABLE_CELLS")
        return [row + [""] * (width - len(row)) for row in value]


class ParseBlock(LegacyBlock):
    type: Literal[
        "title", "heading", "text", "list", "table", "key_value", "figure", "marginalia", "other",
        "page_header", "page_footer"
    ]
    structure: BlockStructure | None

    @model_validator(mode="after")
    def validate_structure(self):
        """Reject detail inconsistent with the block role or table contents.

        Returns:
            This validated block.

        Raises:
            ValueError: If heading, list, or table detail conflicts with the block.
        """
        if self.structure is None:
            return self
        structure = self.structure
        if structure.heading_level is not None and self.type not in {"title", "heading"}:
            raise ValueError("Heading level requires a heading block")
        if structure.list_items is not None:
            if self.type != "list":
                raise ValueError("List items require a list block")
            previous = -1
            for item in structure.list_items:
                if item.depth > previous + 1:
                    raise ValueError("List nesting must start at zero and increase one level at a time")
                previous = item.depth
        if structure.table_cells is not None:
            if self.type != "table" or not self.table or not self.table[0]:
                raise ValueError("Table cells require a nonempty table")
            height, width = len(self.table), len(self.table[0])
            occupied = set()
            for cell in structure.table_cells:
                if cell.row + cell.rowspan > height or cell.column + cell.colspan > width:
                    raise ValueError("Table span exceeds table bounds")
                for row in range(cell.row, cell.row + cell.rowspan):
                    for column in range(cell.column, cell.column + cell.colspan):
                        if (row, column) in occupied:
                            raise ValueError("Table cells overlap")
                        if (row, column) != (cell.row, cell.column) and self.table[row][column]:
                            raise ValueError("Covered table cells must be empty")
                        occupied.add((row, column))
            if len(occupied) != height * width:
                raise ValueError("Table metadata must cover every cell")
        return self


class ParsePage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    page: int
    width_px: int
    height_px: int
    blocks: list[ParseBlock]

    _check_tables = field_validator("blocks", mode="before")(_bounded_blocks)


class LegacyParsePage(BaseModel):
    """Original request contract, retained until detailed extraction passes source review."""
    model_config = ConfigDict(extra="forbid")
    page: int
    width_px: int
    height_px: int
    blocks: list[LegacyBlock]

    _check_tables = field_validator("blocks", mode="before")(_bounded_blocks)

    def to_page(self) -> ParsePage:
        """Convert a validated default-profile page without inventing structure.

        Returns:
            An internal page whose blocks have unknown detailed structure.
        """
        data = self.model_dump()
        data["blocks"] = [{**b, "structure": None} for b in data["blocks"]]
        return ParsePage.model_validate(data)


# Artifact-only metadata. These models are NOT reachable from either strict
# Sol page schema. Keep them here so ParseResult and reconciliation share types
# without an import-time cycle or an unvalidated arbitrary-JSON field.
class _LayoutMetadata(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, allow_inf_nan=False)


Point = tuple[float, float]


class NormalizedLayoutRegion(_LayoutMetadata):
    index: int = Field(ge=0, strict=True)
    class_id: int = Field(ge=0, le=24, strict=True)
    raw_label: str = Field(min_length=1)
    canonical_label: str
    role_hint: str
    score: float = Field(ge=0, le=1)
    box_px: tuple[float, float, float, float]
    polygon_px: tuple[Point, ...]
    bbox: BBox
    polygon: tuple[Point, ...]
    order: int | None = Field(ge=0, lt=300, strict=True)
    box_clipped: bool
    polygon_clipped: bool
    contour_status: Literal["valid", "missing", "unusable"] = "valid"
    contour_source: Literal["mask", "aabb_fallback", "legacy_unknown"] = "legacy_unknown"

    @model_validator(mode="after")
    def validate_geometry(self):
        # Geometry helpers are imported at validation time, after both modules
        # have loaded; importing saved JSON never loads inference dependencies.
        from src.layout_detector import LABELS
        from src.layout_reconcile import ROLE_HINTS, _deduplicate, _validate_polygon
        if self.canonical_label != LABELS[self.class_id] or self.role_hint != ROLE_HINTS[self.canonical_label]:
            raise ValueError("Layout class metadata disagrees")
        if not (self.box_px[0] < self.box_px[2] and self.box_px[1] < self.box_px[3]):
            raise ValueError("Degenerate layout box")
        if not all(math.isfinite(v) and 0 <= v <= 1 for v in (*self.bbox.xyxy, *(v for p in self.polygon for v in p))):
            raise ValueError("Invalid normalized layout geometry")
        if not (self.bbox.xyxy[0] < self.bbox.xyxy[2] and self.bbox.xyxy[1] < self.bbox.xyxy[3]):
            raise ValueError("Degenerate normalized box")
        if self.contour_source == "aabb_fallback" and self.contour_status == "valid":
            raise ValueError("AABB fallback is not a mask contour")
        if self.contour_status == "valid":
            _validate_polygon(_deduplicate(self.polygon_px))
            _validate_polygon(list(self.polygon))
        elif self.polygon or (self.contour_status == "missing" and self.polygon_px):
            raise ValueError("Unavailable contour cannot supply normalized geometry")
        return self


class NormalizedLayoutPage(_LayoutMetadata):
    page: int = Field(ge=1, strict=True)
    width_px: int = Field(ge=1, strict=True)
    height_px: int = Field(ge=1, strict=True)
    regions: tuple[NormalizedLayoutRegion, ...]
    model_id: str
    revision: str
    engine: str
    device: Literal["cpu", "cuda"]
    fallback_reason: Literal["cuda_unavailable", "cuda_probe_failed", "cuda_execution_failed"] | None
    order_base: Literal[0]
    execution_failures: tuple[LayoutFailureStage, ...] = ()

    @model_validator(mode="after")
    def validate_regions(self):
        for i, region in enumerate(self.regions):
            if region.index != i or region.bbox.page != self.page:
                raise ValueError("Invalid layout region identity")
            x0, y0, x1, y1 = region.box_px
            clipped = (max(0, x0), max(0, y0), min(self.width_px, x1), min(self.height_px, y1))
            expected = tuple(v / size for v, size in zip(clipped, (self.width_px, self.height_px) * 2))
            if expected != region.bbox.xyxy:
                raise ValueError("Layout box does not match page dimensions")
        return self


class ReconcilePolicy(_LayoutMetadata):
    min_score: float = Field(default=0.80, ge=0, le=1)
    min_coverage: float = Field(default=0.90, gt=0, le=1)
    min_partial_coverage: float = Field(default=0.25, gt=0, le=1)
    # Historical gates are loadable, but not used by v3-authoritative-v1.
    max_center_distance: float | None = Field(default=None, ge=0, le=1)
    min_iou_margin: float | None = Field(default=None, ge=0, le=1)
    significant_coverage: float = Field(default=0.80, gt=0, le=1)

    def check_active(self):
        """Reject legacy-only gates and inconsistent active coverage settings.

        Raises:
            ValueError: If an inactive gate is set or coverage bounds conflict.
        """
        if self.max_center_distance is not None or self.min_iou_margin is not None:
            raise ValueError("Distance and margin gates are legacy-only policy settings")
        if self.min_partial_coverage > self.min_coverage:
            raise ValueError("Partial coverage cannot exceed containment coverage")


MatchReason = Literal["split", "merge", "many_to_many", "low_score", "weak_overlap", "distant_centers",
                      "not_mutual_best", "ambiguous", "role_disagreement", "label_disagreement",
                      "missing_order", "missing_box", "invalid_box", "no_overlap", "assignment_conflict"]
ReviewFlag = Literal["split", "merge", "many_to_many", "missing_order", "label_alias", "contour_fallback"]


class MatchEvidence(_LayoutMetadata):
    block_index: int = Field(ge=0, strict=True)
    region_index: int = Field(ge=0, strict=True)
    iou: float = Field(ge=0, le=1)
    sol_coverage: float = Field(ge=0, le=1)
    region_coverage: float = Field(ge=0, le=1)
    center_distance: float = Field(ge=0, le=1)
    score: float = Field(ge=0, le=1)
    reasons: tuple[MatchReason, ...] = ()
    review_flags: tuple[ReviewFlag, ...] = ()
    geometry: Literal["polygon", "aabb"] = "aabb"
    geometry_fallback_reason: Literal["missing", "unusable"] | None = None


class BlockDecision(_LayoutMetadata):
    original_index: int = Field(ge=0, strict=True)
    output_index: int = Field(ge=0, strict=True)
    region_index: int | None = Field(ge=0, strict=True)
    reasons: tuple[MatchReason, ...]
    review_flags: tuple[ReviewFlag, ...] = ()


class ReconciliationDetails(_LayoutMetadata):
    policy_version: Literal["conservative-v1", "conservative-v2", "v3-authoritative-v1"] = "conservative-v1"
    policy: ReconcilePolicy
    candidates: tuple[MatchEvidence, ...]
    decisions: tuple[BlockDecision, ...]
    unmatched_region_indices: tuple[int, ...]


class ReconciliationMetadata(ReconciliationDetails):
    layout: NormalizedLayoutPage


class GuideContour(_LayoutMetadata):
    region_index: int = Field(ge=0, strict=True)
    status: Literal["full", "simplified", "omitted"]
    reason: Literal["redundant_box", "budget_or_precision", "missing", "unusable"] | None = None
    max_deviation_px: float = Field(default=0, ge=0, le=1)


class LayoutPageArtifact(_LayoutMetadata):
    layout: NormalizedLayoutPage
    reconciliation: ReconciliationDetails | None = None
    guide_contours: tuple[GuideContour, ...] = ()

    def check_parsed_page(self, parsed: ParsePage | None) -> None:
        """Check at the page boundary as well as when loading an artifact."""
        if parsed is not None and (parsed.page, parsed.width_px, parsed.height_px) != (
                self.layout.page, self.layout.width_px, self.layout.height_px):
            raise ValueError("Layout page dimensions disagree")
        if self.reconciliation is not None:
            if parsed is None or len(parsed.blocks) != len(self.reconciliation.decisions):
                raise ValueError("Reconciliation requires a matching parsed page")
            for decision in self.reconciliation.decisions:
                if decision.region_index is not None:
                    if parsed.blocks[decision.output_index].bbox != self.layout.regions[decision.region_index].bbox:
                        raise ValueError("Reconciled geometry disagrees with artifact")
                    if self.reconciliation.policy_version == "v3-authoritative-v1":
                        from src.layout_reconcile import CLASS_COMPATIBILITY
                        label = self.layout.regions[decision.region_index].canonical_label
                        if parsed.blocks[decision.output_index].type not in CLASS_COMPATIBILITY[label]:
                            raise ValueError("Reconciled class is incompatible with Sol type")

    @model_validator(mode="after")
    def validate_references(self):
        """Enforce unique, in-range guide and one-to-one match references.

        Returns:
            This validated artifact.

        Raises:
            ValueError: If guide, candidate, or accepted-match references disagree.
        """
        if self.guide_contours and (
                sorted(c.region_index for c in self.guide_contours) != list(range(len(self.layout.regions)))):
            raise ValueError("Invalid guide contour references")
        details = self.reconciliation
        if details is None:
            return self
        count, regions = len(details.decisions), set(range(len(self.layout.regions)))
        if ([d.original_index for d in details.decisions] != list(range(count))
                or sorted(d.output_index for d in details.decisions) != list(range(count))):
            raise ValueError("Invalid reconciliation block indices")
        matched = [d.region_index for d in details.decisions if d.region_index is not None]
        if len(matched) != len(set(matched)) or not set(matched) <= regions:
            raise ValueError("Invalid one-to-one region references")
        if tuple(sorted(regions - set(matched))) != details.unmatched_region_indices:
            raise ValueError("Invalid unmatched region references")
        pairs = {(c.block_index, c.region_index): c for c in details.candidates}
        if len(pairs) != len(details.candidates) or any(b >= count or r not in regions for b, r in pairs):
            raise ValueError("Invalid candidate references")
        if details.policy_version == "v3-authoritative-v1":
            details.policy.check_active()
            review_only = {"split", "merge", "many_to_many", "missing_order"}
            for item in (*details.candidates, *details.decisions):
                if review_only.intersection(item.reasons):
                    raise ValueError("Informational flags cannot be rejection reasons")
            for candidate in details.candidates:
                region = self.layout.regions[candidate.region_index]
                expected = "polygon" if region.contour_status == "valid" else "aabb"
                reason = None if expected == "polygon" else region.contour_status
                if (candidate.geometry, candidate.geometry_fallback_reason, candidate.score) != (expected, reason, region.score):
                    raise ValueError("Candidate geometry or score disagrees with region")
        for decision in details.decisions:
            if decision.region_index is not None:
                candidate = pairs.get((decision.original_index, decision.region_index))
                if candidate is None or candidate.reasons:
                    raise ValueError("Accepted match lacks eligible evidence")
                if details.policy_version == "v3-authoritative-v1" and (
                        candidate.score < details.policy.min_score
                        or max(candidate.sol_coverage, candidate.region_coverage) < details.policy.min_coverage
                        or min(candidate.sol_coverage, candidate.region_coverage) < details.policy.min_partial_coverage):
                    raise ValueError("Accepted evidence fails eligibility thresholds")
                if details.policy_version == "v3-authoritative-v1" and (
                        decision.reasons or decision.review_flags != candidate.review_flags):
                    raise ValueError("Accepted decision disagrees with evidence")
        return self


class ParseResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    doc_sha: str
    schema_version: Literal[2] = 2
    extraction_profile: Literal["legacy", "detailed"] = "legacy"
    pages: list[ParsePage]
    content_filtered_pages: list[int] = Field(default_factory=list)
    page_diagnostics: list[PageDiagnostic] = Field(default_factory=list)
    layout_metadata: list[LayoutPageArtifact] = Field(default_factory=list)
    model: str = "gpt-6-sol"

    @model_validator(mode="after")
    def validate_layout_metadata(self):
        """Check saved layout pages against parsed pages and diagnostics.

        Returns:
            This validated document result.

        Raises:
            ValueError: If layout pages or reconciliation references disagree.
        """
        pages = {page.page: page for page in self.pages}
        known_pages = set(pages) | {d.page for d in self.page_diagnostics}
        identities = [entry.layout.page for entry in self.layout_metadata]
        if len(identities) != len(set(identities)) or not set(identities) <= known_pages:
            raise ValueError("Invalid layout page identities")
        for entry in self.layout_metadata:
            entry.check_parsed_page(pages.get(entry.layout.page))
        return self

    @model_validator(mode="before")
    @classmethod
    def load_legacy(cls, value):
        """Upgrade saved legacy artifacts in memory, never live page responses."""
        if isinstance(value, dict):
            check_document_tables(value.get("pages", []))
        if isinstance(value, dict) and "schema_version" not in value:
            value = dict(value)
            value["pages"] = [
                {**page, "blocks": [{"structure": None, **block} if isinstance(block, dict) else block
                                    for block in page.get("blocks", [])]}
                if isinstance(page, dict) else page for page in value.get("pages", [])
            ]
        return value
